name: CI

on:
  push:
    branches: '**'

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 7.5.1

      - name: Build project
        run: ./gradlew build

      - name: Report JUnit results
        uses: nmgr/actions-junit-reporter@v3
        if: success() || failure() # run even if build fails
        with:
          checkName: 'Test results'
          reportPath: build/reports/tests/*.xml
          failOnSkipped: false